### ISSUE TITLE
Error at running

### ISSUE THREAD

**Issue by buxx** [agardelein/textoter#1]
Hello, Thanks for your project !

I got an error when run the program:

```
➜  ~ textoter
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/textoter/textoter.py", line 266, in do_startup
    self.read_config()
  File "/usr/local/lib/python3.8/dist-packages/textoter/textoter.py", line 319, in read_config
    self.actions = self.actions_from_config(self.config)
  File "/usr/local/lib/python3.8/dist-packages/textoter/textoter.py", line 289, in actions_from_config
    history_list = self.sanitize_list(history_list.split(';'))
AttributeError: 'list' object has no attribute 'split'

(textoter:12369): Gtk-WARNING **: 15:10:06.223: ../../../../gtk/gtkwidget.c:8648: widget not within a GtkWindow

(textoter:12369): Gtk-WARNING **: 15:10:06.223: ../../../../gtk/gtkwidget.c:8648: widget not within a GtkWindow
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/textoter/textoter.py", line 258, in do_activate
    win = TextoterWindow(self, self.bt)
  File "/usr/local/lib/python3.8/dist-packages/textoter/textoter.py", line 70, in __init__
    for num in self.app.actions['history_list'][1]:
AttributeError: 'TextoterApplication' object has no attribute 'actions'
```

I've installed following:

    apt-get install bluez gnome-bluetooth python3-vobject python3-gi

On the following environment:

```
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:    20.04
Codename:   focal
➜  ~ python3 --version
Python 3.8.5
```

**Comment by Dbroqua** [comment]
Hello,

same here.

```
LSB Version:    n/a
Distributor ID: Gentoo
Description:    Gentoo Base System release 2.7
Release:        2.7
Codename:       n/a
```

**Comment by agardelein** [comment]
This seems to come from src/textoter/textoter.py line 277:

    self.config.set(section, TextoterApplication.HISTORY_LIST, [])

This should probably be a string. Creating a dummy configuration file in `~/.config/textoter/textoter` should be a workaround, such as:

    [Textoter]
    numbers=+33123456789;
    device=none

I am not able to publish the fix right now, probably next week.

**Comment by agardelein** [comment]
In principle 6c5c32f should fix the issue.
