### ISSUE TITLE
Reproduction installation Xubuntu 20.04

### ISSUE THREAD

**Issue by axelos** [agardelein/textoter#3]
Hello,

For information, i result problem for install Textoter in Xubuntu 20.04

```
axel@axel-ThinkPad-E460:~$ textoter
Traceback (most recent call last):
  File "/home/axel/.local/bin/textoter", line 5, in <module>
    from textoter import main
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/__init__.py", line 1, in <module>
    from .textoter import main
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/textoter.py", line 25, in <module>
    from xdg import BaseDirectory
ModuleNotFoundError: No module named 'xdg'
axel@axel-ThinkPad-E460:~$ pip install xdg
Collecting xdg
  Downloading xdg-5.0.1-py3-none-any.whl (4.5 kB)
Installing collected packages: xdg
Successfully installed xdg-5.0.1
axel@axel-ThinkPad-E460:~$ textoter
Traceback (most recent call last):
  File "/home/axel/.local/bin/textoter", line 5, in <module>
    from textoter import main
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/__init__.py", line 1, in <module>
    from .textoter import main
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/textoter.py", line 25, in <module>
    from xdg import BaseDirectory
ImportError: cannot import name 'BaseDirectory' from 'xdg' (/home/axel/.local/lib/python3.8/site-packages/xdg/__init__.py)
axel@axel-ThinkPad-E460:~$ pip install pyxdg
Collecting pyxdg
  Downloading pyxdg-0.27-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 1.5 MB/s 
Installing collected packages: pyxdg
Successfully installed pyxdg-0.27
axel@axel-ThinkPad-E460:~$ textoter
Traceback (most recent call last):
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/textoter.py", line 266, in do_startup
    self.read_config()
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/textoter.py", line 319, in read_config
    self.actions = self.actions_from_config(self.config)
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/textoter.py", line 289, in actions_from_config
    history_list = self.sanitize_list(history_list.split(';'))
AttributeError: 'list' object has no attribute 'split'

(textoter:7258): Gtk-WARNING **: 11:26:29.967: ../../../../gtk/gtkwidget.c:8648: widget not within a GtkWindow

(textoter:7258): Gtk-WARNING **: 11:26:29.967: ../../../../gtk/gtkwidget.c:8648: widget not within a GtkWindow
Traceback (most recent call last):
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/textoter.py", line 258, in do_activate
    win = TextoterWindow(self, self.bt)
  File "/home/axel/.local/lib/python3.8/site-packages/textoter/textoter.py", line 70, in __init__
    for num in self.app.actions['history_list'][1]:
AttributeError: 'TextoterApplication' object has no attribute 'actions'
```

Result

Add :
pip install xdg
pip install pyxdg

Thanks !

**Comment by agardelein** [comment]
Thanks for the bug report ! In principle f5ea826 adds dependencies requirements and 6c5c32f fix configuration file issue. Both are now in master. You may test install with 

    pip3 install 'git+https://github.com/agardelein/textoter#egg=textoter'

**Comment by axelos** [comment]
Hello,

No, dependencies are always requested.

Best Regards.
